python search_control.py \
   --config_dir  example_generation/train \
   --output_dir example_generation/train_prompting_5 \
   --example_ids 16 44 73 91 93 \
   --search_dir_list train_prompting_5 \
   --num_tasks 1 \
   --num_runs 2 \
   --goal defense \
   --appless \
   --num_processes 10 \
   --max_simulation_round 2 \
   --keep_bank \
   --target_exp_result 1.0 \
   --adaptive_search \
   --prompt_version v1 \
   --no_backtrack \
   --use_mixed_objective \
   --data_sender_model gpt-4.1-mini \
   --data_subject_model gpt-4.1-mini \
   --data_recipient_model gpt-4.1-mini \
   --search_agent_model gpt-5